#task-13 create own csv dataset

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("linux_ds.csv")

In [3]:
df

    student_id name  age  marks
0            1    A   18     45
1            2    B   21     34
2            3    C   19     67
3            4    D   20     89
4            5    E   23     45
5            6    F   18     67
6            7    G   19     78
7            8    H   22     97
8            9    I   20     56
9           10    J   17     87
10          11    K   19     34
11          12    L   18     98
12          13    M   21     45
13          14    N   22      9
14          15    O   23     45
15          16    P   24     32
16          17    Q   17     67
17          18    R   18     78
18          19    S   19     84
19          20    T   20     56
20          21    U   21     53
21          22    V   22     72
22          23    W   23     78
23          24    X   24     42
24          25    Y   25     46
25          26    Z   26     57
26          27    a   17     83
27          28    b   18     92
28          29    c   19     78
29          30    d   20     56
30          31    e   21     43
31          32    f   22     73
32          33    g   23     98
33          34    h   24     90
34          35    i   25     43
35          36    j   26     64
36          37    k   17     75
37          38    l   18     89
38          39    m   19     96
39          40    n   20     54
40          41    o   21     93
41          42    p   22     92
42          43    q   23     91
43          44    r   19     43
44          45    s   20     65
45          46    t   21     89
46          47    u   19     84
47          48    v   20     64
48          49    w   21     98
49          50    x   19     65

In [4]:
df.isnull().sum()

student_id    0
name          0
age           0
marks         0
dtype: int64

In [5]:
df.head()

   student_id name  age  marks
0           1    A   18     45
1           2    B   21     34
2           3    C   19     67
3           4    D   20     89
4           5    E   23     45

In [6]:
df.tail()

    student_id name  age  marks
45          46    t   21     89
46          47    u   19     84
47          48    v   20     64
48          49    w   21     98
49          50    x   19     65

In [7]:
df.describe()

       student_id        age      marks
count    50.00000  50.000000  50.000000
mean     25.50000  20.660000  67.580000
std      14.57738   2.429496  21.798792
min       1.00000  17.000000   9.000000
25%      13.25000  19.000000  47.750000
50%      25.50000  20.000000  67.000000
75%      37.75000  22.000000  88.500000
max      50.00000  26.000000  98.000000

In [8]:
df.shape

(50, 4)

In [9]:
df.columns

Index(['student_id', 'name', 'age', 'marks'], dtype='object')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  50 non-null     int64
 1   name        50 non-null     object
 2   age         50 non-null     int64
 3   marks       50 non-null     int64
dtypes: int64(3), object(1)
memory usage: 1.7+ KB

In [12]:
df.drop_duplicates(df)

    student_id name  age  marks
0            1    A   18     45
1            2    B   21     34
2            3    C   19     67
3            4    D   20     89
4            5    E   23     45
5            6    F   18     67
6            7    G   19     78
7            8    H   22     97
8            9    I   20     56
9           10    J   17     87
10          11    K   19     34
11          12    L   18     98
12          13    M   21     45
13          14    N   22      9
14          15    O   23     45
15          16    P   24     32
16          17    Q   17     67
17          18    R   18     78
18          19    S   19     84
19          20    T   20     56
20          21    U   21     53
21          22    V   22     72
22          23    W   23     78
23          24    X   24     42
24          25    Y   25     46
25          26    Z   26     57
26          27    a   17     83
27          28    b   18     92
28          29    c   19     78
29          30    d   20     56
30          31    e   21     43
31          32    f   22     73
32          33    g   23     98
33          34    h   24     90
34          35    i   25     43
35          36    j   26     64
36          37    k   17     75
37          38    l   18     89
38          39    m   19     96
39          40    n   20     54
40          41    o   21     93
41          42    p   22     92
42          43    q   23     91
43          44    r   19     43
44          45    s   20     65
45          46    t   21     89
46          47    u   19     84
47          48    v   20     64
48          49    w   21     98
49          50    x   19     65

In [13]:
df.drop("name", axis = 1, inplace = True)

In [14]:
df.head()

   student_id  age  marks
0           1   18     45
1           2   21     34
2           3   19     67
3           4   20     89
4           5   23     45

In [15]:
print("Average Marks:", df["marks"].mean())
print("Highest Marks:", df["marks"].max())
print("Lowest Marks:", df["marks"].min())

Average Marks: 67.58
Highest Marks: 98
Lowest Marks: 9